-- 1. Habilitar la extensión PostGIS (Geospatial)
create extension if not exists postgis;

-- 2. Crear tabla de Lugares Turísticos
create table public.lugares (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  categoria text,
  -- Columna espacial para guardar latitud/longitud (WGS84)
  ubicacion geography(POINT, 4326),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Insertar datos de prueba (Ej: Coordenadas del Centro de Málaga)
insert into public.lugares (nombre, categoria, ubicacion)
values
  ('Centro de Málaga', 'Turismo', ST_Point(-4.4214, 36.7213)),
  ('Parque Tecnológico', 'Tech', ST_Point(-4.5539, 36.7367));

-- 4. Habilitar seguridad (Row Level Security) - Estándar en Supabase
alter table public.lugares enable row level security;

-- Permitir lectura pública de los mapas
create policy "Lectura pública de mapas"
  on public.lugares for select
  using ( true );
